//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec UI


namespace rec UI


namespace rec UI

module UI =
    open UI

    let error_ =
        Optics.lens (fun (data: UI) -> data.error) (fun (value: string option) (data: UI) -> { data with error = value })

    let whatsOnYourMind_ =
        Optics.lens (fun (data: UI) -> data.whatsOnYourMind) (fun (value: string) (data: UI) ->
            { data with whatsOnYourMind = value })

    let posts_ =
        Optics.lens (fun (data: UI) -> data.posts) (fun (value: Post list) (data: UI) -> { data with posts = value })
